### ISSUE TITLE
Please add "my performance" endpoint to API

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [iconomi-ag/iconomi-api#11]
Currently it's possible to get the user balance with  
`https://api.iconomi.com/v1/user/balance`  
But I'm not able to view **my performance** (user performance) in the API

![image](https://user-images.githubusercontent.com/5278928/110255833-86d56d00-7f74-11eb-8eb0-e93a4560d94b.png)

It would be very useful to have an endpoint like this, but for the User's performance  

![image](https://user-images.githubusercontent.com/5278928/110255917-f186a880-7f74-11eb-84ba-622601eb8493.png)

**Comment by iconomi-support** [comment]
Hello,

An endpoint for this has been added. See documentation at https://iconomi-ag.github.io/iconomi-api/#operation/portfolioHistory

Best Regards,
Iconomi Team
