### ISSUE TITLE
Receiving 401 (unauthorised) while requesting to POST /v1/strategies/{ticker}/structure

### ISSUE THREAD

**Issue by 3clypse** [iconomi-ag/iconomi-api#17]
Hi!

I'm an user of your platform and I'm trying to modify the structure using the following endpoint (without luck): https://iconomi-ag.github.io/iconomi-api/#operation/structure

## Issue
- Receiving `401 (unauthorised)` when making a request to `POST /v1/strategies/{ticker}/structure`
- `ticker` obviously is replaced with my strategy ticker ID (and I'm the owner))
### Thinking loud 🤔 
- I may have an issue with the body payload while generating the signature and that could be the cause (?) 🤔 
- At the same time, the documentation of this endpoint seems to be outdated(?) or maybe I'm a bit lost/missing something. What's exactly that <authorizations> ? I though all endpoints with mandatory authentication were  using the following: https://iconomi-ag.github.io/iconomi-api/#section/Authentication 🤔 
![image](https://user-images.githubusercontent.com/11727815/120121170-3b60e280-c1a2-11eb-8b04-c86c6490271d.png)

Below you'll find the steps I made so far, trying to resolve this issue:

## Request working nice (with authentication)
- `GET https://api.iconomi.com/v1/user/balance`
- Request authentication made following https://iconomi-ag.github.io/iconomi-api/#section/Authentication
- The API key I used for this has all permissions (read + trading + withdraw)
- Signature made with `{timestamp}GET/v1/user/balance` Eg: `'1622410754356GET/v1/user/balance'`
- Receiving `200 status code`
- Receiving something like (is way longer) `{'currency': 'USD', ...}` as response.

## Request not working for me (with Python)
- `POST /v1/strategies/{ticker}/structure`
- Request authentication made following https://iconomi-ag.github.io/iconomi-api/#section/Authentication
- The API key I used for this has all permissions (read + trading + withdraw)
- Signature made with `{timestamp}POST/v1/strategies/{ticker}/structure` Eg: `1622410754943POST/v1/strategies/123456789/structure"{\\"ticker\\":\\"123456789\\",\\"values\\":[{\\"assetTicker\\":\\"USDC\\",\\"rebalancedWeight\\":0.9},{\\"assetTicker\\":\\"ETH\\",\\"rebalancedWeight\\":0.1}],\\"speedType\\":\\"SLOW\\"}"'`
- Receiving `401 status code`

## Request not working for me (with Ruby)
> I tried with Ruby, given Python scapes backslashes with other backslashes (`\\`) and I though that was the issue 🤔 
- `POST /v1/strategies/{ticker}/structure`
- Request authentication made following https://iconomi-ag.github.io/iconomi-api/#section/Authentication
- The API key I used for this has all permissions (read + trading + withdraw)
- Signature made with `{timestamp}POST/v1/strategies/{ticker}/structure` Eg: `"1622410181781POST/v1/strategies/123456789/structure{\"ticker\":\"123456789\",\"values\":[{\"assetTicker\":\"USDC\",\"rebalancedWeight\":0.9},{\"assetTicker\":\"ETH\",\"rebalancedWeight\":0.1}],\"speedType\":\"FAST\"}"'`
- Receiving `401 status code`

Thank you in advance! 👍

**Comment by matejsp** [comment]
Hi, it seems that what are you sending and signing is not the same and also it is not properly structured. 
You are escaping JSON payload and this means that signature is not valid as well. What you have send to us is escaped again.

Your signature (in our logs with replaced ticker):
```
1622410754943POST/v1/strategies/123456789/structure"\"{\\\"ticker\\\":\\\"CA269A7CB63F4E95A63FEB9FAF7905\\\",\\\"values\\\":[{\\\"assetTicker\\\":\\\"USDC\\\",\\\"rebalancedWeight\\\":0.9},{\\\"assetTicker\\\":\\\"ETH\\\",\\\"rebalancedWeight\\\":0.1}],\\\"speedType\\\":\\\"SLOW\\\"}\""
```

However it should be like this (before signing):

```
1622410754943POST/v1/strategies/123456789/structure{"ticker":"123456789","values":[{"assetTicker":"USDT","rebalancedWeight":0.9},{"assetTicker":"ETH","rebalancedWeight":0.1}],"speedType":"SLOW"}
```

And body that you send MUST be the 100% same when posting (unescaped).

Hope it helps.

**Comment by 3clypse** [comment]
Thanks for that quick reply 🙇 

EDIT: It's working on Postman, so is clearly an issue from my side (on the code or related with the language while transforming data types).

Closing this issue, given is not a failure from your side. I'll update as soon I find what's wrong on the code.

Thank you for your time.
