### ISSUE TITLE
Websockets not working?

### ISSUE THREAD

**Issue by jesusthatsgreat** [iconomi-ag/iconomi-api#2]
I might be missing something but the docs say websockets are publicly available yet when testing a connection to **wss://ws-api-v1.iconomi.net/** via native HTML 5 Websocket API it gives an error, sample code here: https://codesandbox.io/s/xv143456jq

`Error in connection establishment: net::ERR_NAME_NOT_RESOLVED`

Are there any restrictions not documented?

**Comment by mvidmar** [comment]
Hi,

thanks for the report. The correct endpoint is wss://api.iconomi.com/v1/ws

The documentation has also been updated.
