### ISSUE TITLE
Posting more then 7 assets to my strategy results in null response

### ISSUE THREAD

**Issue by fluxwise** [iconomi-ag/iconomi-api#22]
Writing my own code in PHP to communicate with the Iconomi API.

Retrieving balance, strategies, structure and so on works fine. Posting a new structure to my strategy works fine too, unless I post more then 7 assets. Is that some kind of limit/bug? The API doesn't return anything with 8+ assets posted, just _null_ as a response.

Eg, this payload works :

$params['values'] = [
['assetTicker' => 'LUNA', 'rebalancedWeight' => 0.2],
['assetTicker' => 'ATOM', 'rebalancedWeight' => 0.15],
['assetTicker' => 'BTC', 'rebalancedWeight' => 0.1],
['assetTicker' => 'ETH', 'rebalancedWeight' => 0.1],
['assetTicker' => 'SOL', 'rebalancedWeight' => 0.15],
['assetTicker' => 'DOT', 'rebalancedWeight' => 0.15],
['assetTicker' => 'AVAX', 'rebalancedWeight' => 0.15],
];

This doesn't :
$params['values'] = [
['assetTicker' => 'LUNA', 'rebalancedWeight' => 0.2],
['assetTicker' => 'ATOM', 'rebalancedWeight' => 0.15],
['assetTicker' => 'BTC', 'rebalancedWeight' => 0.1],
['assetTicker' => 'ETH', 'rebalancedWeight' => 0.1],
['assetTicker' => 'SOL', 'rebalancedWeight' => 0.15],
['assetTicker' => 'DOT', 'rebalancedWeight' => 0.15],
['assetTicker' => 'AVAX', 'rebalancedWeight' => 0.10],
['assetTicker' => 'ALGO', 'rebalancedWeight' => 0.05],
];

**Comment by 3clypse** [comment]
+1 The same here. What's going on with the API?

**Comment by iconomi-support** [comment]
Hey,
the number of assets is not the problem, the issue is somewhere else. We have added additional logging to diagnose these issues faster, but we can’t help you more without additional information - when did you perform the request, what was the response and the response code, and what strategy did you try to change.

Regards,

ICONOMI Team
