### ISSUE TITLE
Getting 400 HTTP status response with +5 or more assets on the strategy

### ISSUE THREAD

**Issue by 3clypse** [iconomi-ag/iconomi-api#24]
Hi, 

While trying to POST with Postman or Python onto `https://api.iconomi.com/v1/strategies/<ticker>/structure` with 11 assets, Iconomi returns 200 ✅ 
But if I add 12 or more assets, I get a 400 error :(

This is some kind of limit from Iconomi backend?

Thank you!

**Comment by 3clypse** [comment]
# Issue

## Scenario A: Example of failed strategy modification via API with 19 assets

### Request Body 
> {"ticker": "xxxxxx", "values": [{"assetTicker": "USDT", "rebalancedWeight": 0.2}, {"assetTicker": "ETH", "rebalancedWeight": 0.15}, {"assetTicker": "BTC", "rebalancedWeight": 0.11}, {"assetTicker": "LUNA", "rebalancedWeight": 0.09}, {"assetTicker": "CRV", "rebalancedWeight": 0.06}, {"assetTicker": "BNB", "rebalancedWeight": 0.04}, {"assetTicker": "SOL", "rebalancedWeight": 0.04}, {"assetTicker": "AVAX", "rebalancedWeight": 0.04}, {"assetTicker": "LINK", "rebalancedWeight": 0.04}, {"assetTicker": "DOT", "rebalancedWeight": 0.03}, {"assetTicker": "MANA", "rebalancedWeight": 0.03}, {"assetTicker": "RVN", "rebalancedWeight": 0.03}, {"assetTicker": "KAVA", "rebalancedWeight": 0.03}, {"assetTicker": "CHR", "rebalancedWeight": 0.03}, {"assetTicker": "XRP", "rebalancedWeight": 0.02}, {"assetTicker": "MATIC", "rebalancedWeight": 0.02}, {"assetTicker": "RUNE", "rebalancedWeight": 0.02}, {"assetTicker": "ADA", "rebalancedWeight": 0.01}, {"assetTicker": "ATOM", "rebalancedWeight": 0.01}], "speedType": "SLOW"}

### Response
Then, API replies with `400` and empty message.

## Scenario B
If I remove assets till they're 5 (obviously having in mind that the weight needs to sum 100%), API returns `200`

## Note
This issue started happening on "Nov 11th at around 12pm GMT time".
Before this time, I had not issues while rebalancing or modifying the strategy.

Thank you

**Comment by iconomi-support** [comment]
Hello,

Is the issue still happening? This is generally not related to the number of assets but rather their specific weight and value (can't have 1% BTC in a strategy that has 10$ in it for example).

If the issue is still happening, can you provide the exact timestamp of the requests?

Best regards,
Iconomi team

**Comment by 3clypse** [comment]
This is not happening anymore. Thank you.
