### ISSUE TITLE
✨ Add `/strategies/{ticker}/posts`

### ISSUE THREAD

**Issue by Rikj000** [iconomi-ag/iconomi-api#25]
## Feature Request
It would be lovely to have a `/strategies/{ticker}/posts` endpoint available! 🙂

With one of those I could write a bot that periodically scans for new news posts of strategy owners & then forwards them to Discord through a WebHook. And that's only one of the many implementations that would be possible with an endpoint like this! 😄

I would also implement an optional parameter `amount`, 
to define the X last messages to be fetched and make it default to something reasonable like the 10 last posts 
*(keeps the load/data transfer of the endpoint light, but should usually be enough posts)*

**Comment by iconomi-support** [comment]
A new endpoint has been added for strategy posts.

See documentation at: https://iconomi-ag.github.io/iconomi-api/#operation/posts

Best regards,
Iconomi Team

**Comment by Rikj000** [comment]
Thanks guys!
