### ISSUE TITLE
websocket documentation corrections

### ISSUE THREAD

**Issue by jesusthatsgreat** [iconomi-ag/iconomi-api#3]
Under the heading "DAA price feed" in the [docs](https://www.iconomi.com/api-docs#tag/WebSocket-feed), the sample request provided is incorrect. "daaTicker" just needs to be renamed to "ticker". It's the same issue under the heading 'DAA Details' where using "daaTicker" as per the documentation won't return anything but using "ticker" will.

# Broken (in documentation)
```
{
    "type":"subscribe",
    "channel": "daa/price",
    "daaTicker": "BLX"
}
```

# Working (not in documentation)
```
{
    "type":"subscribe",
    "channel": "daa/price",
    "ticker": "BLX"
}
```

Also very minor typo I found in docs under the heading 'historical information':
"...can be returned based on the **lenght** of the period"

**Comment by mvidmar** [comment]
Thanks again. Fixed and updated.
