### ISSUE TITLE
/v1/strategy endpoint pageSize broken and limited to 255

### ISSUE THREAD

**Issue by markmarijnissen** [iconomi-ag/iconomi-api#36]
It seems ICONOMI only has 255 public strategies:

- `https://api.iconomi.com/v1/strategies` will return 255 entries
- `https://api.iconomi.com/v1/strategies?pageSize=1000` will return 255 entries
- `https://api.iconomi.com/v1/strategies?pageSize=250` will return 250 entries, but `https://api.iconomi.com/v1/strategies?pageSize=250&pageNumber=1` will only return 4 entries

However, this is incorrect, I expect many more such as ` 20XCOINSINDEX`
 
- it does not include "20XCOINSINDEX"
- `https://api.iconomi.com/v1/strategies/20XCOINSINDEX` does return statistics for this one.
- More are missing, like `FUTUREPOWERFUND` 
- Missing strategies are public viewable on the ICONOMI website, so no security issues here.

**Comment by iconomi-support** [comment]
Hello,

We have checked, and the pagination appears to work correctly.
* `pageSize=1000` returns 255 entries - there are 255 publicly visible strategies on our platform
* `pageSize=250` returns 250 entries, `pageSize=250&pageNumber=1` returns 5 entries, totaling 255

You can see the same list of strategies on the platform at https://www.iconomi.com/strategies.
Strategies like `20XCOINSINDEX` and `FUTUREPOWERFUND` are visible for the public, but aren't searchable. You will not find them in the search on our platform, but you can access them directly by URL.

Best regards,
Iconomi team
