### ISSUE TITLE
Portfolio structure weights need more decimal places

### ISSUE THREAD

**Issue by jesusthatsgreat** [iconomi-ag/iconomi-api#4]
The weights being returned by the **daa/{ticker}/structure** endpoint currently aren't usable due to the fact they only provide 2 decimal places.

This means that if an asset within a portfolio has a weight of less than 0.5%, it will be returned as zero value. This is the case with many portfolios that have a large number of assets. For example BLX currently has 29 assets with 9 of them showing zero weights because 9 assets have a weight of less than 0.5%

https://api.iconomi.com/v1/daa/BLX/structure

# Example 
> {
>             "rebalancedWeight": 0,
>             "targetWeight": 0,
>             "assetTicker": "ICX",
>             "assetName": "Icon",
>             "assetCategory": "Platform"
>         }

Increasing decimal places on rebalancedWeight & targetWeight from 2 to 4 or more would fix the problem

**Comment by mvidmar** [comment]
Agreed, a mistake in the specifications as it should be 2 decimal places on the percentage value.

Documentation updated and new api version released with 4 decimal places.
