### ISSUE TITLE
500 error on /pricehistory endpoint when query string is used

### ISSUE THREAD

**Issue by jesusthatsgreat** [iconomi-ag/iconomi-api#5]
For example the following returns a 500 error:
https://api.iconomi.com/v1/daa/CAR/pricehistory?from=1551110510&to=1558800110

https://api.iconomi.com/v1/daa/CAR/pricehistory (without any query string) works as expected. It had been working fine with the query string, not sure when it stopped working but randomly noticed it earlier today. 

![err](https://user-images.githubusercontent.com/35536996/58372069-36605d00-7f10-11e9-9553-3acc9f46d68b.PNG)

**Comment by ctomc** [comment]
Thank you for reporting.

It should work as expected now.
