### ISSUE TITLE
Null prices being returned for all portfolios 

### ISSUE THREAD

**Issue by jesusthatsgreat** [iconomi-ag/iconomi-api#6]
https://api.iconomi.com/v1/daa/BLX/price returns null for price

https://api.iconomi.com/v1/daa/BLX/pricehistory returns successful 200 response but no data

I assume the two are related and null prices aren't intentional :)

**Comment by ctomc** [comment]
Hey
you have correctly assumed that problems with price and price  history endpoints are related.

It should be fixed now.
