### ISSUE TITLE
targetWeight missing from API response

### ISSUE THREAD

**Issue by jesusthatsgreat** [iconomi-ag/iconomi-api#7]
When getting crypto fund structure from the API, targetWeight is no longer contained in the results:

![current-weight](https://user-images.githubusercontent.com/35536996/64413988-7b0ca000-d08a-11e9-875a-61498ca8f072.PNG)

The API documentation site still has targetWeight included in sample response / expected values: https://api.iconomi.com/#tag/REST-API/paths/~1v1~1daa~1{ticker}~1structure/get

**Comment by ctomc** [comment]
Hey @jesusthatsgreat thank you for report.
We found the issue and already fixed it. 
Sorry for any problems it might cause you.
