### ISSUE TITLE
Request: returns % over different time frames for Crypto Strategies

### ISSUE THREAD

**Issue by jesusthatsgreat** [iconomi-ag/iconomi-api#8]
I *think* this may have been available previously on the API but in any case it's not in documentation and not being returned in any responses at the minute so it would be nice to have.

If the returns percentages over different timeframes are available it makes comparing / ranking Crypto Strategies much easier.

![returns](https://user-images.githubusercontent.com/35536996/73209863-06252a00-4141-11ea-901c-67189b42255e.PNG)

**Comment by ctomc** [comment]
Hey, 
returns ware wrongly shown on price endpoint, which was recently fixed to match documentation.
Said that, we are working on few new endpoints one of which will focus on this.

Is there any other info you would like to see on api in general?

**Comment by jesusthatsgreat** [comment]
Volatility & drawdown would be useful via the api for those time periods too. If they were available I’d definitely use them to help visualise differences between crypto strategies.

Another thing I’d like is a list of all supported coins/tokens on the platform - I know these are added to & removed occasionally which can be confusing. An endpoint listing all currently supported coins would be useful as a sanity check and help me to figure out when coins have been added/removed.

The only other thing I can think of at the minute is the last rebalance time for each crypto strategy. Or even better - all rebalance times of a crypto strategy along with all changes made. 

Looking forward to the new endpoints and including any of the above would useful from my perspective 👍

**Comment by ctomc** [comment]
We added statistics endpoint that includes volatility & drawdawn.
example: https://api.iconomi.com/v1/strategies/BLX/statistics

we added last rebalance time as well as currenty monthly counter of rebalances for strategy to structure endpoint.
https://api.iconomi.com/v1/strategies/BLX/structure

New assets endpoint ware added, but currently they only list directly "tradeable" assets on platform.
In next update endpoint will include also data about assets supported in strategies along with its statuses.

**Comment by ctomc** [comment]
assets endpoint was updated to list all platform supported assets together with flags in what scenarios are they supported for as well as status.

https://api.iconomi.com/v1/assets
I think this addresses your suggestions.

If you have issues / suggestions please create new issue.
